### ISSUE TITLE
Dependency conflict around @typescript-eslint/eslint-plugin

### ISSUE THREAD

**Issue by packetship** [bloomui/tokyo-free-black-react-admin-dashboard#1]
Hi,

I've pulled from the 'main' branch and I'm getting a dependency conflict in the initial 'npm install':

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tokyo-free-black-react-admin-dashboard@1.1.0
npm ERR! Found: @typescript-eslint/eslint-plugin@5.0.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/eslint-plugin@"^4.29.3" from eslint-config-airbnb-typescript@14.0.1
npm ERR! node_modules/eslint-config-airbnb-typescript
npm ERR!   dev eslint-config-airbnb-typescript@"14.0.1" from the root project
npm ERR! 

```
I tried updating everything to latest (with 'npx npm-check-updates -u') and that allowed 'npm install' to complete, but unfortunately it looks like there are new lint errors which break your current code.

Any ideas?

Many thanks

Paul

**Comment by packetship** [comment]
Update / workround:

Pulling eslint-config-airbnb-typescript to latest fixes the dependency problem without introducing other issues:

`npm i eslint-config-airbnb-typescript@latest`

This then allows 'npm install' to complete but it then won't run because of missing eslint config:

`Failed to load config "react-app" to extend from.`

I haven't found a way to install eslint-config-react-app yet without causing more dependency nightmares.

**Comment by sandtreader** [comment]
Resolved:  Needs node 14, I had 12 - nvm is my friend now!

**Comment by packetship** [comment]
Resolved: Needs node 14, I had 12 - nvm is my friend now!
